monolog:
    channels:
        - deprecation

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!doctrine"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            # Regular application logs (info and above only)
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.main.log"
                level: info
                channels: ["!event", "!deprecation"]
                formatter: monolog.formatter.logstash

            # Error trigger that creates comprehensive error logs (including debug)
            error_trigger:
                type: fingers_crossed
                action_level: error
                handler: errors_file
                excluded_http_codes: [404, 405]
                buffer_size: 50
                channels: ["!event", "!deprecation"]

            errors_file:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.errors.log"
                level: debug
                formatter: monolog.formatter.logstash

            # Regular console handler (maintains default output behavior)
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!deprecation"]

            # Suppress deprecation logs completely in production
            deprecation:
                type: "null" # Send to nowhere
                channels: ["deprecation"]
