twig:
    file_name_pattern: "*.twig"

    paths:
        "src/Common/Presentation/Resources/templates": "common.presentation"
        "src/WebsiteContent/Presentation/Resources/templates": "website_content.presentation"
        "src/Account/Presentation/Resources/templates": "account.presentation"
        "src/McpInstancesManagement/Presentation/Resources/templates": "mcp_instances_management.presentation"

when@test:
    twig:
        strict_variables: true
